name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Netcup Server
        uses: appleboy/ssh-action@master
        with:
          host: 46.38.249.14
          username: hosting242051
          password: ${{ secrets.SSH_PASSWORD }}
          script: ~/darkocekovski.com/deploy.sh
